HidingOak_Text_SpawnOaks::
    .string "Spawning a new selection of Oaks$"

HidingOak_Text_HuntNotStarted::
    .string "It's blank$"

HidingOak_Text_HuntSuccess::
    .string "You win!$"

HidingOak_Text_HuntFailure::
    .string "You didn't win ... yet\p"
    .string "You've only found {STR_VAR_1} of {STR_VAR_2}$"

HidingOak_Text_NewlyFoundOak::
    .string "Haha! Well done {PLAYER}!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}\p"
    .string "Now then, let's see\n"
    .string "what you can do...$"

HidingOak_Text_DefeatedOak::
    .string "Bravo {PLAYER}!\n"
    .string "Very well done indeed.$"

HidingOak_Text_PreviouslyFoundOak::
    .string "My secret passphrase is:$"

HidingOak_Text_SecretPhrase_1::
    .string "{COLOR GREEN}It was a dark and stormy night$"

HidingOak_Text_SecretPhrase_2::
    .string "{COLOR GREEN}and the skipper said to the mate$"

HidingOak_Text_SecretPhrase_3::
    .string "{COLOR GREEN}Mate, tell me a story$"

HidingOak_Text_SecretPhrase_4::
    .string "{COLOR GREEN}and this is the story he told$"

HidingOak_Text_SecretPhrase_5::
    .string "{COLOR GREEN}It was a bright and peaceful day$"
