name: CI/CD

on:
  push:
    branches: [ develop ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GAME_VERSION: FIRERED
      GAME_LANGUAGE: ENGLISH
      GAME_REVISION: 0
      MODERN: 1
      COMPARE: 0
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: 'develop'

      - name: Checkout agbcc
        uses: actions/checkout@master
        with:
          path: 'agbcc'
          repository: 'pret/agbcc'

      - name: Install binutils
        run: sudo apt install gcc-arm-none-eabi binutils-arm-none-eabi
        # build-essential, git, and libpng-dev are already installed
        # gcc-arm-none-eabi is only needed for the modern build
        # as an alternative to dkP

      - name: Install agbcc
        run: |
          ./build.sh
          ./install.sh ../
        working-directory: ./agbcc

      - name: Build
        run: |
          make -j${nproc}

      - name: Calculate Version
        id: version
        uses: paulhatch/semantic-version@v4.0.2
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          format: "${major}.${minor}"
          bump_each_commit: true

      - name: Release
        uses: actions/create-release@v1
        id: create-release
        with:
          release_name: v${{ steps.version.outputs.version}}
          tag_name: v${{ steps.version,outputs.version_tag }}

      - name: Upload ROM
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./pokefirered.gba
          asset_name: ProfOakHideNSeek.gba
          asset_content_type: application/zip
